### ISSUE TITLE
Releasing 1.0

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-java#3]
## Background

This repository (`mapbox-java`) contains two new artifacts, `mapbox-java-services` and `mapbox-android-services` which are the result of combining the original `mapbox-geocoder-android` and `mapbox-directions-android` projects as discussed in https://github.com/mapbox/gl-internal/issues/387#issuecomment-200399195.

### New features

Besides combining our previous libraries, the codebase now has a number of additional features:
- Separates the pure Java code (e.g. for server use) from the Android-specific code.
- Includes support for v5 of the upcoming directions API.
- Supports the Mapbox Static API.
- Supports RxJava for all geocoding and directions requests in addition to the classic `Call` mechanism.
- Includes a lightweight implementation for Java GeoJSON objects.
- Includes additional tests.

## Release checklist

- [x] Documentation
  - [x] Complete Javadoc for classes @cammace @danswick 
  - [x] Extract sample Android code from the TestApp for the website @cammace @danswick
  - [x] Prepare `CHANGELOG.md` @zugaldia
  - [x] Decide the final location for Javadoc and samples in https://www.mapbox.com/android-sdk/ @danswick @cammace https://github.com/mapbox/mapbox-java/issues/9
- [x] Release a version of Sirius that uses `mapbox-android-services` without legacy libraries @bleege @zugaldia https://github.com/mapbox/sirius-android/issues/276
- [x] General code review @tobrun @bleege 
- [x] Comms: Blog post et al. @Lndsay @zugaldia https://github.com/mapbox/blog/pull/1107
- [x] Make this repo public.
- [x] Publish artifacts to Maven Central @zugaldia
- [x] Add deprecation notice in previous repos.

## After-release checklist

- [x] Include Java as a new language in Mapbox's new API Documentation site https://github.com/mapbox/api-documentation/issues/138 @tmcw @cammace @danswick 

/cc: @1ec5 @bsudekum @twbell @lxbarth @gundersen

**Comment by bleege** [comment]
:boom: 

Congrats @zugaldia @cammace @danswick @tobrun @twbell for making this happen!

**Comment by zugaldia** [comment]
Mapbox Android Services was released yesterday and announced via https://www.mapbox.com/blog/mapbox-android-services. All items in the checklist have been completed or ticketed for follow up.

Congrats everyone on the launch!
