### ISSUE TITLE
2.0.0 docs release checklist 

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-java#382]
- [ ] Rearrange headings into functional groups: 
    + REST APIs
    + Navigation
    + Telemetry
    + Utilities 
- [ ] Fix section headings hash functionality (could have something to do with ignored H1s)
- [ ] Filter content by Maps SDK and Mapbox Java with top buttons
- [ ] Add links to relevant examples in each section
    + Add icon to examples element to denote a demo is avail in the demo app
- [ ] Fix search
- [ ] Add link (external) to Android examples page along header
- [ ] Fix various responsive UI bugs 
    + [ ] ToC dropdown hides under the search bar 
    + [ ] Footer thingy in ToC overruns the rest of ToC when height is low
- [ ] Add / edit doc content 
    + [ ] All map SDK parts
    + [ ] Update navigation section
    + [ ] Add other REST APIs 
    + [ ] Add utilities section and include:
        + [ ] Add Turf section 
        + [ ] Line simplification
        + [ ] Tidy
        + [ ] GeoJSON
        + [ ] Android-ui

**Comment by cammace** [comment]
Closing this ticket since we now have https://github.com/mapbox/android-docs which resolves some of these issues listed out here.
